// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PlanningPoker.Persistence;

#pragma warning disable 219, 612, 618
#nullable enable

namespace MyCompiledModels
{
    [DbContext(typeof(PlanningPokerDbContext))]
    public partial class PlanningPokerDbContextModel : RuntimeModel
    {
        static PlanningPokerDbContextModel()
        {
            var model = new PlanningPokerDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static PlanningPokerDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
