// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace MyCompiledModels
{
    public partial class PlanningPokerDbContextModel
    {
        partial void Initialize()
        {
            var game = GameEntityType.Create(this);
            var round = RoundEntityType.Create(this);
            var team = TeamEntityType.Create(this);
            var userStory = UserStoryEntityType.Create(this);

            GameEntityType.CreateForeignKey1(game, team);
            GameEntityType.CreateForeignKey2(game, userStory);
            RoundEntityType.CreateForeignKey1(round, game);
            UserStoryEntityType.CreateForeignKey1(userStory, team);

            GameEntityType.CreateAnnotations(game);
            RoundEntityType.CreateAnnotations(round);
            TeamEntityType.CreateAnnotations(team);
            UserStoryEntityType.CreateAnnotations(userStory);

            AddAnnotation("ProductVersion", "6.0.5");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
